name: Prebuild
on:
  workflow_dispatch:
jobs:
  prebuild-apple:
    strategy:
      matrix:
        include:
        - os: macos-12
          platform: darwin
          arch: x64
        - os: macos-14
          platform: darwin
          arch: arm64
        - os: macos-14
          platform: ios
          arch: arm64
        - os: macos-14
          platform: ios
          arch: arm64
          tags: -simulator
          flags: --simulator
        - os: macos-14
          platform: ios
          arch: x64
          tags: -simulator
          flags: --simulator
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.tags }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/cache@v4
      with:
        path: vendor/bare/corestore
        key: corestore-${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.tags }}
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm install -g bare-dev
    - run: bare-dev configure --platform ${{ matrix.platform }} --arch ${{ matrix.arch }} ${{ matrix.flags }}
    - run: bare-dev build
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.tags }}
        path: build/apple/*.dylib
  prebuild-android:
    strategy:
      matrix:
        include:
        - os: ubuntu-22.04
          platform: android
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/cache@v4
      with:
        path: vendor/bare/corestore
        key: corestore-${{ matrix.platform }}
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
    - run: npm install -g bare-dev
    - run: bare-dev android sdk licenses accept
    - run: bare-dev build --gradle
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform }}
        path: android/build/outputs/aar/*-release.aar
