name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-apple:
    strategy:
      matrix:
        include:
        - os: macos-14
          platform: darwin
          arch: x64
        - os: macos-14
          platform: darwin
          arch: arm64
        - os: macos-14
          platform: ios
          arch: arm64
        - os: macos-14
          platform: ios
          arch: arm64
          tags: -simulator
          flags: --simulator
        - os: macos-14
          platform: ios
          arch: x64
          tags: -simulator
          flags: --simulator
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.tags }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/cache@v4
      with:
        path: build/corestore
        key: corestore-${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.tags }}
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - run: npm install -g bare-make
    - run: npm install
    - run: npm install --prefix vendor/bare
    - run: bare-make generate --platform ${{ matrix.platform }} --arch ${{ matrix.arch }} ${{ matrix.flags }} --debug
    - run: bare-make build
  test-android:
    strategy:
      matrix:
        include:
        - os: ubuntu-22.04
          platform: android
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/cache@v4
      with:
        path: android/build/corestore
        key: corestore-${{ matrix.platform }}
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
    - run: npm install
    - run: npm install --prefix vendor/bare
    - run: gradle build
